### ISSUE TITLE
17AB1-5-A and 18AC1-3-A can't perform NPT

### ISSUE THREAD

**Issue by starwingc** [starwingc/peptoid_24summer#10]
The simulation looks flying everywhere after doing the npt
Can check out their path 

`/peptoid/17AB1-5-A/GAFF/neutral/gaff1/`
`peptoid/18AC1-3-A/GAFF/neutral/gaff1/`

![image](https://github.com/starwingc/peptoid_24summer/assets/152640562/434f714d-0a6c-4b58-be9d-baf05350d026)

**Comment by vvoelz** [comment]
I debugged 17AB1-5-A and got it to work.  Two things were going on:

1. There was an BUG in acpype that wrote a crazy number for the mass of one of the ACE carbons
![image](https://github.com/starwingc/peptoid_24summer/assets/123431/c956565b-01e8-41d2-881b-bcbd050bafb9)

2. The Parrinello-Rahman barostat seems to unstable for equilibration. I changed it to Berendsen and just to be safe ame it generate new velocities, so it's no longer `continuation = yes`.  I made the following changes to the `mdp/npt.mdp`  file:

```
; Bond parameters
continuation            = no       ; don't reuse velocities from the NVT

; Pressure coupling is on
pcoupl                  = Berendsen        ; Pressure coupling NPT - VAV: more stable that Par-Ram for equil
tau_p                   = 5.0              ; time constant, in ps - VAV: this is the default

; Velocity generation
gen_vel                 = yes        ; Velocity generation is ON -- need initial Maxwell-Boltzman velocities
```

@starwingc  -- see if this works for you, and also see if similar issues might be the source of the problems with 18AC1-3-A!

**Comment by starwingc** [comment]
it works for 17AB1-5-A , however, for the same setting for 18AC1-3-A, this error appear:

```
Command line:
  gmx mdrun -nt 1 -v -s npt_sol.tpr -c npt_sol.gro -o npt_sol.trr


Back Off! I just backed up md.log to ./#md.log.1#
Compiled SIMD: SSE4.1, but for this host/run AVX2_256 might be better (see
log).
Reading file npt_sol.tpr, VERSION 2020.5 (single precision)
Note: file tpx version 119, software tpx version 122
Changing nstlist from 10 to 100, rlist from 1 to 1

Using 1 MPI thread
Using 1 OpenMP thread 


NOTE: Thread affinity was not set.

-------------------------------------------------------
Program:     gmx mdrun, version 2021.4
Source file: src/gromacs/utility/smalloc.cpp (line 227)

Fatal error:
Not enough memory. Failed to allocate 18446744072295088128 aligned elements of
size 8 for lin
(called from file /tmp/gromacs-2021.4/src/gromacs/fft/fft5d.cpp, line 442)

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
```
