### ISSUE TITLE
Problem with prepared three residues 

### ISSUE THREAD

**Issue by starwingc** [starwingc/peptoid_24summer#2]
Hi @vvoelz , I am unable to prepared these three residues:

NMA, NXA, NXB under the `residues/GAFF/modified/`
all the file are created and checked, can you have a looks at them?

**Comment by vvoelz** [comment]
Sure -- I'll take a look!  Which script breaks down, and at what point? Is there an error message?

**Comment by starwingc** [comment]
simply the `build_amber_residue.py`, I don't have the error message right now, but it is `index out of list`. While all other residues are run fine!

**Comment by vvoelz** [comment]
Hi @starwingc -- all of those residues have quatenary amines, and should be positive charged.  There's a flag in the `build_amber_residue.py` script the specify the net charges (See: `residues/GAFF/modified/NMA/runme_vav` e.g.).  I built the residues and pushed the results.

**Comment by starwingc** [comment]
[heart]         Starwing Chen reacted to your message:
________________________________
From: Vincent Voelz ***@***.***>
Sent: Thursday, May 23, 2024 3:13:03 PM
To: starwingc/peptoid_24summer ***@***.***>
Cc: Starwing Chen ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [starwingc/peptoid_24summer] Problem with prepared three residues (Issue #2)


Hi @starwingc<https://github.com/starwingc> -- all of those residues have quatenary amines, and should be positive charged. There's a flag in the build_amber_residue.py script the specify the net charges (See: residues/GAFF/modified/NMA/runme_vav e.g.). I built the residues and pushed the results.

**Comment by starwingc** [comment]
[like]  Starwing Chen reacted to your message:
________________________________
From: Vincent Voelz ***@***.***>
Sent: Thursday, May 23, 2024 3:13:03 PM
To: starwingc/peptoid_24summer ***@***.***>
Cc: Starwing Chen ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [starwingc/peptoid_24summer] Problem with prepared three residues (Issue #2)


Hi @starwingc<https://github.com/starwingc> -- all of those residues have quatenary amines, and should be positive charged. There's a flag in the build_amber_residue.py script the specify the net charges (See: residues/GAFF/modified/NMA/runme_vav e.g.). I built the residues and pushed the results.
