### ISSUE TITLE
Issue with doing the NVT with 19AE1-4-A

### ISSUE THREAD

**Issue by starwingc** [starwingc/peptoid_24summer#6]
Hi @vvoelz 
I have problem doing the NVT step. 
the test file are in `peptoid_24summer/test-output/test`, and all the things are fine until the nvt step.
the error are in `gmx_nvt.pf.e1915819` 

```
Fatal error:
2672 particles communicated to PME rank 4 are more than 2/3 times the cut-off
out of the domain decomposition cell of their charge group in dimension x.
This usually means that your system is not well equilibrated.
```

I look at the `em.gro` in VMD, the molecules seems intact, which is one possible reason of simulation being broken down in [Answer1](https://gitlab.com/gromacs/gromacs/-/issues/3412), [Answer2](https://www.researchgate.net/post/Gromacs_Error_2_particles_communicated_to_PME_rank_3_are_more_than_2_3_times_the_cut-off_out_of_the_domain_How_to_solve_this_error)

![image](https://github.com/starwingc/peptoid_24summer/assets/152640562/249697a0-0b13-4a2d-a926-07c5f76e3bb2)

![image](https://github.com/starwingc/peptoid_24summer/assets/152640562/50f7a74a-1ce0-46aa-9e18-fa863c63ee7e)

Also, I try to increase the number of step, decrease the dt, and enlarge the box diameter from 1 to 1.5. They are both not working. 

The forcefield I am using is: **AMBER99SB-ILDN**
The water I am using is: **TIP3P**

All the commend and changes in the top file are recorded in the `runme` file, and the original output are under the same path `peptoid_24summer/test-output/`

**Comment by vvoelz** [comment]
Hi @starwingc -- where are you performing these calculations?   If Owlsnest, you may be using too many processors for the numbers of atoms in your system.    One way you can test if this is the case is by using the `mdrun -nt 1` flag, which restricts the calculation to one thread.  This is a typical problem at early minimization and equilibration of systems, when particles may cross too many domain decomposition boundaries to be efficient.

**Comment by starwingc** [comment]
> Hi @starwingc -- where are you performing these calculations? If Owlsnest, you may be using too many processors for the numbers of atoms in your system. One way you can test if this is the case is by using the `mdrun -nt 1` flag, which restricts the calculation to one thread. This is a typical problem at early minimization and equilibration of systems, when particles may cross too many domain decomposition boundaries to be efficient.

I try using this flag, but it seems that it doesn't works :

```

Command line:
  gmx mdrun -v -nt 1 -s nvt.tpr -c 19AE1-4-A_protonated_ions.gro


Back Off! I just backed up md.log to ./#md.log.1#
Compiled SIMD: SSE4.1, but for this host/run AVX2_256 might be better (see
log).
Reading file nvt.tpr, VERSION 2021.2 (single precision)
Changing nstlist from 10 to 100, rlist from 1 to 1

Using 1 MPI thread
Using 1 OpenMP thread


NOTE: Thread affinity was not set.

Back Off! I just backed up traj.trr to ./#traj.trr.1#

Back Off! I just backed up ener.edr to ./#ener.edr.1#
starting mdrun '19AE1-4-A_protonated in water'
50000 steps,    100.0 ps.
^Mstep 0/var/spool/torque/mom_priv/jobs/1916046.SC: line 16:  3311 Segmentation fault      gmx mdrun -v -nt 1 -s nvt.tpr -c 19AE1-4-A_protonated_ions.gro

```

**Comment by vvoelz** [comment]
@starwingc - I figured it out!

There is a problem with ACYPE (?) where CRAZY large numbers are written for certain atoms.
In `19AE1-4-A_protonated_GMX.top` the two NH2 hydrogens are affected:
```
...
    80   h1     4   NPE   H14   80     0.046961      1.00800 ; qtot 3.000
    81    N     5   NHE     N   81    -0.463000     14.01000 ; qtot 2.537
    82    H     5   NHE   HN1   82     0.231500 3533694130000000305166266993565950479143406426100339323737831785571024896.00000 ; qtot 2.769
    83    H     5   NHE   HN2   83     0.231500 3533694130000000305166266993565950479143406426100339323737831785571024896.00000 ; qtot 3.000
```

Setting these to their correct masses fixes the problem.

**Comment by starwingc** [comment]
I solve the issue by changing the format of top file to avoid creating crystal (?) water 

```
; Include force field parameters
#include "/usr/local/gromacs/share/gromacs/top/amber99.ff/forcefield.itp"

; Include Peptoid
#include "./19AE1-4-A_protonated.itp"

; Include TIP3P water model
#include "/usr/local/gromacs/share/gromacs/top/amber99.ff/tip3p.itp"

; Include Ion model
#include "/usr/local/gromacs/share/gromacs/top/amber99.ff/ions.itp"

[ system ]
19AE1-4-A_protonated in water

[ molecules ]
; Compound        nmols
 19AE1-4-A_protonated 1
SOL         1669
CL               3
```
